:recycle: Decouple the token autogeneration from the study/program question
We now have a program with a mode of interest (e-bike) that wants to use
autogenerated tokens (denver CASR). So we decouple the token generation method
from whether it is evaluating an intervention or not.

TODO: we should really decouple the question of whether there is an
intervention also from study vs. program. Study vs. program was a useful
shortcut while beginning to define the configs but is turning out to be too
rigid now.

Summary of changes:
- Define an "opcode" section of the config which indicates whether the token
should be autogenerated or not, and whether it should include subgroups or
not.
- create an OPCODE_AUTOGEN variable that, in a backwards compatible fashion,
  indicates whether the opcode should be autogenerated or not
- change all the study/program checks to check OPCODE_AUTOGEN instead
- while determining the subgroups, handle the case where the opcode section
  does not exist in the config
- change the text to indicate that the opcode is generated by the platform, not
  necessarily in the phone app

Testing done:

-- check the change

```
    "intro": {
        "program_or_study": "program",
        "subgroups": ["low-income-regular", "unrestricted-regular",
            "low-income-cargo", "unrestricted-cargo"],
```

http://localhost:3274/?study_config=denver-casr&sub_group=low-income-regular
says to use provided token

```
    "opcode": {
        "autogen": true,
        "subgroups": ["low-income-regular", "unrestricted-regular",
            "low-income-cargo", "unrestricted-cargo"]
    },
```

http://localhost:3274/?study_config=denver-casr
Error: Subgroup null not found in list low-income-regular,unrestricted-regular,low-income-cargo,unrestricted-cargo

http://localhost:3274/?study_config=denver-casr&sub_group=low-income-regular
autogenerates token

-- Check for regressions

http://localhost:3274/?study_config=open-access&sub_group=low-income-regular
autogenerates token

http://localhost:3274/?study_config=caeb-co&sub_group=low-income-regular
says to use provided token